### ISSUE TITLE
[5pt] graph-prototype: Port unported blocks

### ISSUE THREAD

**Issue by frankosterfeld** [fair-acc/gr-digitizers#116]
Port - or declare abandoned - the following blocks:

- [ ] cascade_sink (old implementation mostly commented out) -> to be implemented as sub-graphs in the new graph-prototype/GR 4.0 framework
- [ ] block_aggregation, 
- [ ] block_amplitude_and_phase, 
- [ ] block_complex_to_mag -> @drslebedev 
- [ ] block_custom_filter, 
- [ ] amplitude_phase_adjuster, 
- [ ] amplitude_and_phase_helper (some are helper blocks, some are hier blocks using old GR3 blocks not yet ported, etc.)
- [X] stft_algorithms (convenience hier block) -> @drslebedev 

blocks shall become core of graph-prototype/GR4.0

**Comment by alexxcons** [comment]
> cascade_sink (old implementation mostly commented out)

One of the most used blocks in the currently running Digitizer Flowgraphs. You can take a look on all used flowgraphs here:

https://gitlab.com/al.schwinn/DigitizerDU2/-/tree/master/src/test

Postmortem sinks, interlock sinks and frequency sinks currently are disabled / untested, since not used with the current FESA software. Insufficient manpower to integrate them. Though afaik with the new opencmw implementation, these as well should be taken into operation.

So if you plan to abandon the Cascade Sink, I suppose we would need some replacement. (I suppose the use-case this sink fulfills could as well be solved by using hieratical blocks)

> block_aggregation

Used inside the cascade sink, so same as above.

> block_amplitude_and_phase, block_complex_to_mag, amplitude_phase_adjuster, amplitude_and_phase_helper

To be used inside dal009 ... dal014 (In order to measure and compare HF frequencies). Some of these blocks are currently disabled in the flowgraphs, since they cause performance problems.

> block_custom_filter, 

Afaik currently unused, though not sure.

> stft_algorithms (convenience hier block)

Currently used for multiple scopes which measure in triggered mode: dal005, dal006, dal027, fel0013 ... e.g. for the schottky_band_pass_filter

**Comment by RalphSteinhagen** [comment]
Largely being implemented and further blocks being tracked by this [EPIC](https://github.com/fair-acc/gnuradio4/issues/161)
